let calculation=localStorage.getItem('calculation') || '';
        function add1(ope){
            calculation+=ope;
            document.querySelector('.output').innerHTML=calculation;
            saveCalculation();
        }
        document.querySelector('.one').addEventListener('click',()=>{
            add1('1');
        })
        document.querySelector('.two').addEventListener('click',()=>{
            add1('2');
        })
        document.querySelector('.three').addEventListener('click',()=>{
            add1('3');
        })
        document.querySelector('.plus').addEventListener('click',()=>{
            add1('+');
        })
        document.querySelector('.four').addEventListener('click',()=>{
            add1('4');
        })
        document.querySelector('.five').addEventListener('click',()=>{
            add1('5');
        })
        document.querySelector('.six').addEventListener('click',()=>{
            add1('6');
        })
        document.querySelector('.minus').addEventListener('click',()=>{
            add1('-');
        })
        document.querySelector('.seven').addEventListener('click',()=>{
            add1('7');
        })
        document.querySelector('.eight').addEventListener('click',()=>{
            add1('8');
        })
        document.querySelector('.nine').addEventListener('click',()=>{
            add1('9');
        })
        document.querySelector('.multiply').addEventListener('click',()=>{
            add1('*');
        })
        document.querySelector('.zero').addEventListener('click',()=>{
            add1('0');
        })
        document.querySelector('.point').addEventListener('click',()=>{
            add1('.');
        })
        document.querySelector('.equalTo').addEventListener('click',()=>{
            calculation=eval(calculation);
            document.querySelector('.output').innerHTML=calculation;
            saveCalculation();
        })
        document.querySelector('.division').addEventListener('click',()=>{
            add1('/');
        })
        document.querySelector('.clearAll').addEventListener('click',()=>{
            calculation='';
            document.querySelector('.output').innerHTML=calculation;
            saveCalculation();
        })
        function saveCalculation() {
            localStorage.setItem('calculation',calculation);
        }